kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-storage
spec:
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
